// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/products": {
            "get": {
                "description": "ดึงรายการรหัสสินค้าและบาร์โค้ดทั้งหมดในระบบ",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "List products",
                "responses": {
                    "200": {
                        "description": "ดึงรายการสินค้าสำเร็จ",
                        "schema": {
                            "$ref": "#/definitions/products.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "เพิ่มรหัสสินค้าและสร้างบาร์โค้ดตามมาตรฐาน Code 39",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Create product",
                "parameters": [
                    {
                        "description": "รหัสสินค้า",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/products.CreateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "สร้างบาร์โค้ดสำเร็จ",
                        "schema": {
                            "$ref": "#/definitions/products.APIResponse"
                        }
                    },
                    "400": {
                        "description": "ข้อมูลไม่ถูกต้อง",
                        "schema": {
                            "$ref": "#/definitions/products.APIResponse"
                        }
                    },
                    "500": {
                        "description": "เกิดข้อผิดพลาดภายในระบบ",
                        "schema": {
                            "$ref": "#/definitions/products.APIResponse"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "delete": {
                "description": "ลบรหัสสินค้าออกจากระบบตาม ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Delete product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ลบข้อมูลสำเร็จ",
                        "schema": {
                            "$ref": "#/definitions/products.APIResponse"
                        }
                    },
                    "400": {
                        "description": "ID ไม่ถูกต้อง",
                        "schema": {
                            "$ref": "#/definitions/products.APIResponse"
                        }
                    },
                    "404": {
                        "description": "ไม่พบข้อมูล",
                        "schema": {
                            "$ref": "#/definitions/products.APIResponse"
                        }
                    },
                    "500": {
                        "description": "เกิดข้อผิดพลาดภายในระบบ",
                        "schema": {
                            "$ref": "#/definitions/products.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "products.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "products.CreateProductRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "ABCD-1234-EFGH-5678"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Product Barcode Management API",
	Description:      "API สำหรับจัดการรหัสสินค้าและบาร์โค้ด (Code 39)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
